# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Ben Lipton's blog
email: ben.lipton@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This summer I'm going to be doing some work on the FreeIPA project, and I
  will use this space to talk about some of what I'm doing and write down
  things I've figured out. Hopefully they will be useful to somebody, or at
  least to me when I forget them later.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://blog.benjaminlipton.com" # the base hostname & protocol for your site
github_username: LiptonB

# Build settings
markdown: kramdown
