[tool.poetry]
name = "blog"
version = "0.1.0"
description = ""
authors = ["Ben Lipton <ben.lipton@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
pelican = "^4.8.0"
markdown = "^3.4.1"
ghp-import = "^2.1.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
